### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
   "Name" : "xiaoyi",
   "Password" : "123456"
}

### Demo
GET http://localhost:8080/exam/demo
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InhpYW95aSIsImV4cCI6MTY4ODM4NjUwN30.bOUGTInnwdlStb57ZmnaGs5nFrjek2L13_GOfizFprQ

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name" : "xiaoyi",
  "email" : "xiaoyi@icloud.com",
  "password" : "123456",
  "roleName" : "ADMIN"
}