### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
   "email" : "xiaoyi@icloud.com",
   "password" : "123456"
}

### Demo
GET http://localhost:8080/exam/demo
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODg3MjAwMjcsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6InhpYW95aUBpY2xvdWQuY29tIn0.Ee2ZrX_pfpI0cuYkmWiemO2SaiJ9-zYEEY0OjOQU-a4

### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name" : "xiaoyi",
  "email" : "xiaoyi@icloud.com",
  "password" : "123456",
  "roleName" : "ADMIN"
}

### Logout
GET http://localhost:8080/exam/logout
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODg2Mzc3ODgsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6InhpYW95aUBpY2xvdWQuY29tIn0.f1gRCIwvn5VV6fWjXYnpHk8SsCN07L4YoErR1QrDY0A


