### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
   "email" : "xiaoyi@icloud.com",
   "password" : "123456"
}

### Demo
GET http://localhost:8080/exam/demo
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODk3NTE2MzAsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6InhpYW95aUBpY2xvdWQuY29tIiwicm9sZSI6IlVTRVIifQ.isYQqjc46_vagrKCtXHqHwj536-0iX5w8G5qrYTtIm0


### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name" : "xiaoyi",
  "email" : "xiaoyi@icloud.com",
  "password" : "123456"
}

### Logout
GET http://localhost:8080/exam/logout
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODk2NjA5MTYsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6InhpYW95aUBpY2xvdWQuY29tIiwicm9sZSI6IlVTRVIifQ.DjkfLJpKuiOJPQ_dqfogqjEF6letg4CHY9af5wpmbH0


### SaveServer
POST http://localhost:8080/server/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODk3NTE2MzAsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6InhpYW95aUBpY2xvdWQuY29tIiwicm9sZSI6IlVTRVIifQ.isYQqjc46_vagrKCtXHqHwj536-0iX5w8G5qrYTtIm0
Content-Type: application/json

{
  "name" : "xiaoyi_first",
  "labels" : [
    "a","b","c","d","e"
  ]
}


### SaveChannel
POST http://localhost:8080/channel/save/30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODk2NjEyODUsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6InhpYW95aUBpY2xvdWQuY29tIiwicm9sZSI6IlVTRVIifQ.YG-pzXdU1N6dX3z7cbU-SIC1XQm005KpzROZcDBjpwE
Content-Type: application/json

{
  "name" : "xiaoyi_first",
  "label" : "example"
}


###
POST http://localhost:8080/serverMember/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODkzMTU1ODYsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6IlN1cGVyQHN1cGVyLmNvbSIsInJvbGUiOiJTVVBFUiJ9.4LEjPZg_ZUA3_iewaKZJ6ddcxL50DovGTHbsxRxzBQk
Content-Type: application/json

{
  "server_id" : 30,
  "member_name" : "xiaoyi",
  "invite_id" : ""
}


###
POST http://localhost:8080/message/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODkzMTU1ODYsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6IlN1cGVyQHN1cGVyLmNvbSIsInJvbGUiOiJTVVBFUiJ9.4LEjPZg_ZUA3_iewaKZJ6ddcxL50DovGTHbsxRxzBQk
Content-Type: application/json

{
  "type" : 0,
  "content" : "你好"
}


###
POST http://localhost:8080/identity/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRyYWN0QXQiOjE2ODkzMTU1ODYsImlzTG9nZ2VkT3V0IjpmYWxzZSwibmFtZSI6IlN1cGVyQHN1cGVyLmNvbSIsInJvbGUiOiJTVVBFUiJ9.4LEjPZg_ZUA3_iewaKZJ6ddcxL50DovGTHbsxRxzBQk
Content-Type: application/json

{
  "name" : "one",
  "server_id" : 30,
  "member_role" : "adm"
}
